apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mazen
  name: springgmetric
spec:
  restartPolicy: Never
  containers:
    - name: springcontainermetric
      image: docker.io/mezzeddine/springmetric:v0
      ports:
        - containerPort: 8080
          name: brom
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: springserviceinsidemetric
#  labels:
#    app: strimzi
#spec:
#  selector:
#    app: strimzi
#  ports:
#    - port: 80
#      name: metrics
#      targetPort: 8080
#  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mypodmonitor
  labels:
    app: mazen
spec:
  selector:
    matchLabels:
      app: mazen
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: brom
      interval: 5s
